Repository prgrms-web-devcourse/Team-Saiko-BidMarket-BE, pull requests merged in 2022-07, with the labels that each got.

#2 [BM-98] :construction_worker: husky 커밋메시지 지라티켓 자동화
  .gitignore
  .husky/prepare-commit-msg
  package-lock.json
  package.json
Labels: CI/CD

#7 [BM-64] 잘못 import 된 @NotNull 라이브러리 변경
  build.gradle
  src/main/java/com/saiko/bidmarket/product/entity/Image.java
  src/main/java/com/saiko/bidmarket/product/entity/Product.java
Labels: Fix

#8 [BM-114] :see_no_evil: 컨테이너 스크립트 폴더 git ignore 추가
  .gitignore
Labels: Environment

#17 [BM-64] :sparkles: product_schema sql 수정
  src/main/resources/sql/product/product_schema.sql
  src/main/resources/sql/schema.sql
Labels: Fix

#23 [BM-128] :bug: 상품 상세조회 응답 객체 카테고리 필드 수정
  src/main/java/com/saiko/bidmarket/product/Category.java
  src/main/java/com/saiko/bidmarket/product/controller/ProductDetailResponse.java
  src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
Labels: Fix

#25 [BM-133] :construction_worker: CODEOWNERS 추가
  .github/CODEOWNERS
Labels: Environment

#32 [BM-141] :construction_worker: 배포 관련 설정
  .github/workflows/deploy.yml
  appspec.yml
  build.gradle
  scripts/gh_deploy.sh
  src/main/resources/application.yaml
Labels: CI/CD

#35 [BM-141] :bug: 배포 관련 버그 수정
  .github/workflows/deploy.yml
  appspec.yml
  build.gradle
  scripts/gh_deploy.sh
  src/main/resources/application.yaml
Labels: CI/CD, Fix

#36 [BM-141] sql 누락 수정
  src/main/resources/application.yaml
Labels: Fix
