Repository prgrms-web-devcourse/Team-Saiko-BidMarket-BE, pull requests merged in 2022-08, with the labels that each got.

#40 [BM-131] :white_check_mark: ProductCustomRepository 테스트 추가
  src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
Labels: Test

#45 [BM-178] :heavy_plus_sign: lombok 의존성 추가
  build.gradle
Labels: Environment

#46 [BM-163] :sparkles: 배치 처리 기능 구현
  build.gradle
  src/main/java/com/saiko/bidmarket/Application.java
  src/main/java/com/saiko/bidmarket/common/config/ScheduledConfig.java
  src/main/java/com/saiko/bidmarket/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/saiko/bidmarket/common/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/saiko/bidmarket/user/entity/Permission.java
  src/test/java/com/saiko/bidmarket/product/SchedulerTest.java
  src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
Labels: Feature

#63 [BM-67] 경매 종료 스케줄러 구현
  src/main/java/com/saiko/bidmarket/common/config/ScheduledConfig.java
  src/main/java/com/saiko/bidmarket/product/repository/ProductRepository.java
  src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
  src/main/java/com/saiko/bidmarket/product/service/ProductService.java
  src/test/java/com/saiko/bidmarket/product/SchedulerTest.java
  src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
Labels: Feature

#64 [BM-182] 유저 판매한 상품 조회 Service, Repository 메서드 구현
  src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepository.java
  src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/saiko/bidmarket/product/repository/dto/UserProductSelectQueryParameter.java
  src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
  src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
  src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java
Labels: Feature

#67 [BM-188] :sparkles: 입찰 목록 조회 controller 구현
  src/main/java/com/saiko/bidmarket/bidding/controller/dto/BiddingCreateResponse.java
  src/main/java/com/saiko/bidmarket/bidding/entity/Bidding.java
  src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectRequest.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectResponse.java
  src/main/java/com/saiko/bidmarket/user/entity/User.java
  src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
  src/main/java/com/saiko/bidmarket/user/service/UserService.java
  src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
Labels: Feature

#70 [BM-193] 경매 종료 스케줄러 테스트 시간 수정
  src/test/java/com/saiko/bidmarket/product/SchedulerTest.java
Labels: Fix, Test

#72 [BM-194] 경매 종료 여부 필드 수정
  src/main/java/com/saiko/bidmarket/product/entity/Product.java
  src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
Labels: Fix

#73 [BM-195] Bidding Fk Fetch Type 변경(Lazy -> EAGER)
  src/main/java/com/saiko/bidmarket/bidding/entity/Bidding.java
Labels: Feature

#82 [BM-202] :recycle: 상품 등록 title 길이 제한 수정 (16 -> 32)
  src/main/java/com/saiko/bidmarket/product/entity/Product.java
  src/main/resources/sql/product/product_schema.sql
  src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
Labels: Refactor

#83 [BM-203] :sparkles: 상품 검색 조건 추가 구현
  src/main/java/com/saiko/bidmarket/product/Sort.java
  src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java
  src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java
  src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
  src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
  src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
Labels: Feature

#100 [BM-257] :adhesive_bandage: notification.sql 위치 변경
  src/main/resources/application.yaml
Labels: Fix

#113 [BM-268] executeClosingProduct 인자 변경(컬렉션 -> 단일 객체)
  src/main/java/com/saiko/bidmarket/common/config/ScheduledConfig.java
  src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
  src/main/java/com/saiko/bidmarket/product/service/ProductService.java
  src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
Labels: Refactor

#112 [BM-267] :fire: IdEncoder 제거
  src/main/java/com/saiko/bidmarket/common/util/IdEncoder.java
  src/test/java/com/saiko/bidmarket/common/util/IdEncoderTest.java
  src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
Labels: Fix

#116 [BM-279] bidding 객체 Fetch Type 수정
  src/main/java/com/saiko/bidmarket/bidding/entity/Bidding.java
Labels: Fix

#115 [BM-269] :recycle: Sort 패키지 변경
  src/main/java/com/saiko/bidmarket/bidding/respository/BiddingCustomRepositoryImpl.java
  src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentSelectRequest.java
  src/main/java/com/saiko/bidmarket/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/saiko/bidmarket/common/Sort.java
  src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java
  src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/saiko/bidmarket/product/repository/dto/UserProductSelectQueryParameter.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectRequest.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserProductSelectRequest.java
  src/test/java/com/saiko/bidmarket/bidding/repository/BiddingRepositoryTest.java
  src/test/java/com/saiko/bidmarket/comment/controller/CommentApiControllerTest.java
  src/test/java/com/saiko/bidmarket/comment/repository/CommentRepositoryTest.java
  src/test/java/com/saiko/bidmarket/comment/service/DefaultCommentServiceTest.java
  src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
  src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
  src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
  src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java
Labels: Refactor

#120 [BM-288] :beers: 알림 메세지 내용 수정
  src/main/java/com/saiko/bidmarket/notification/NotificationType.java
Labels: Fix

#122 [BM-291] :adhesive_bandage: 알림 엔티티 필드 수정
  src/main/java/com/saiko/bidmarket/notification/entity/Notification.java
  src/main/java/com/saiko/bidmarket/notification/event/NotificationCreateHandler.java
  src/main/resources/sql/notification/notification_schema.sql
Labels: Fix

#133 [BM-298] :recycle: url 수정
  src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java
  src/main/java/com/saiko/bidmarket/product/controller/ProductApiController.java
  src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
Labels: Refactor

#132 [BM-293] :recycle: offset long 타입으로 변경
  src/main/java/com/saiko/bidmarket/notification/controller/dto/NotificationSelectRequest.java
  src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java
  src/main/java/com/saiko/bidmarket/product/repository/dto/UserProductSelectQueryParameter.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectRequest.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserProductSelectRequest.java
Labels: Refactor

#135 [BM-299] :recycle: 상품 엔티티 location 제약 조건 추가
  src/main/java/com/saiko/bidmarket/product/controller/dto/ProductCreateRequest.java
  src/main/java/com/saiko/bidmarket/product/entity/Product.java
  src/main/resources/sql/product/product_schema.sql
  src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
Labels: Refactor

#143 [BM-308] :adhesive_bandage: heart schema 위치 변경
  src/main/resources/application.yaml
Labels: Fix

#144 [BM-308] 상품 데이터 경매 만료날짜 연장
  src/main/resources/sql/product/product_data.sql
Labels: Fix, Refactor

#146 [BM-310] :adhesive_bandage: 낙찰자 선정 수정
  src/main/java/com/saiko/bidmarket/product/entity/Product.java
Labels: Fix

#151 [BM-314] :bug: updatedAt 어노테이션 수정
  src/main/java/com/saiko/bidmarket/common/entity/BaseTime.java
Labels: Fix

#153 [BM-316] :bug: stomp cors제거 (임시)
  src/main/java/com/saiko/bidmarket/common/config/WebSocketConfig.java
Labels: Fix

#158 [BM-321] type, typeId null 처리 수정
  src/main/java/com/saiko/bidmarket/report/entity/Report.java
Labels: Fix

#161 [BM-330] :construction_worker: 어플리케이션 시간 동기화
  src/main/java/com/saiko/bidmarket/Application.java
Labels: Environment

#165 [BM-330] :construction_worker: Application 시간 동기화 (단 1줄)
  scripts/gh_deploy.sh
Labels: Environment

#168 [BM-316] :bug: cors 설정 변경
  src/main/java/com/saiko/bidmarket/common/config/WebSocketConfig.java
Labels: Fix

#172 [BM-331] :recycle: 상품 생성, 상품 조회, 상품 검색, 댓글 등록, 댓글 조회 id 검증 로직 제거
  src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentCreateRequest.java
  src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentSelectRequest.java
  src/main/java/com/saiko/bidmarket/comment/service/DefaultCommentService.java
  src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
  src/test/java/com/saiko/bidmarket/comment/controller/CommentApiControllerTest.java
  src/test/java/com/saiko/bidmarket/comment/service/DefaultCommentServiceTest.java
  src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
Labels: Refactor

#166 [BM-312] :sparkles: 채팅방 생성 스케줄러 연동
  src/main/java/com/saiko/bidmarket/chat/service/ChatRoomService.java
  src/main/java/com/saiko/bidmarket/chat/service/DefaultChatRoomService.java
  src/main/java/com/saiko/bidmarket/common/config/ScheduledConfig.java
  src/test/java/com/saiko/bidmarket/chat/service/DefaultChatRoomServiceTest.java
  src/test/java/com/saiko/bidmarket/product/SchedulerTest.java
Labels: Feature

#173 [BM-335] :sparkles: 낙찰 결과 확인 api 응답에 낙찰 금액 추가
  src/main/java/com/saiko/bidmarket/product/controller/dto/BiddingResultResponse.java
  src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
  src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
  src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
Labels: Feature

#174 [BM-336] :sparkles: 댓글 전체 조회 응답에 댓글 아이디 추가
  src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentSelectResponse.java
  src/test/java/com/saiko/bidmarket/comment/controller/CommentApiControllerTest.java
Labels: Feature

#180 [BM-345] :adhesive_bandage: 필드명 수정
  src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatPublishMessage.java
  src/test/java/com/saiko/bidmarket/chat/controller/ChatWebSocketControllerTest.java
Labels: Fix

#179 [BM-323] :recycle: 입찰한 상품 조회 리팩토링
  src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
  src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectRequest.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectResponse.java
  src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
  src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
Labels: Refactor

#184 [BM-354] 비딩 금액 조회 인자 수정
  src/main/java/com/saiko/bidmarket/bidding/controller/BiddingApiController.java
  src/main/java/com/saiko/bidmarket/bidding/service/DefaultBiddingService.java
Labels: Fix

#187 [BM-358] :adhesive_bandage: heartCount응답필드 추가
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectResponse.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserHeartSelectResponse.java
  src/main/java/com/saiko/bidmarket/user/controller/dto/UserProductSelectResponse.java
  src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
Labels: Fix

#188 [BM-364] :bug: Transactional 애노테이션 추가
  src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
Labels: Fix

#189 [BM-340] 리드미 작성
  README.md
Labels: Environment

#191 [BM-367] :bug: 더티체킹 안되는거 픽스
  src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
Labels: Fix

#192 [BM-368] :bug: builder 수정
  src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
Labels: Fix

#190 [BM-319] validator 응답 타입 변환 및 리팩토링
  src/main/java/com/saiko/bidmarket/report/service/DefaultReportService.java
  src/main/java/com/saiko/bidmarket/report/service/ReportValidator.java
  src/main/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForComment.java
  src/main/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForProduct.java
  src/main/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForUser.java
  src/main/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteStrategy.java
  src/test/java/com/saiko/bidmarket/report/service/ReportValidatorTest.java
  src/test/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForCommentTest.java
  src/test/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForProductTest.java
  src/test/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForUserTest.java
Labels: Refactor

#198 [BM-383] :bug: claims role 가져오는 부분 추가
  src/main/java/com/saiko/bidmarket/common/jwt/Jwt.java
Labels: Fix
